import { BaseStateMachine } from "./base-state-machine";
import { UCanvas, Matrix, Point } from "@/uni_modules/u-canvas";
// #ifdef WEB
import { WheelDirection, PointerwheelEvent } from "@/uni_modules/u-pointer"
// #endif
import {
	PointerclickEvent,
	PointerdownEvent,
	PointermoveEvent,
	PointerupEvent,
	PointercancelEvent,
} from "@/uni_modules/u-pointer";

export class SelectionStateMachine extends BaseStateMachine {
	constructor(canvas : UCanvas) {
		super(canvas);
	}

	public override onpointerclick(e : PointerclickEvent) : void {
		const point = this.canvas.toCanvasPoint(new Point(e.pointer.x, e.pointer.y));
		const hitTarget = this.canvas.root.hitTest(point);
	}

	public override onpointerdown(e : PointerdownEvent) : void {
		console.log("onpointerdown");
	}

	public override onpointermove(e : PointermoveEvent) : void {
		const translate = this.canvas.matrix!.apply(new Point(e.pointer.delta.x, e.pointer.delta.y));

		this.canvas.matrix.setTranslate(translate.x, translate.y);
		this.canvas.render();
	}

	public override onpointerup(e : PointerupEvent) : void { }

	public override onpointercancel(e : PointercancelEvent) : void { }

	// #ifdef WEB
	public override onpointerwheel(e : PointerwheelEvent) : void {
		const point = this.canvas.toCanvasPoint(new Point(e.pointer.x, e.pointer.y));
		const factor = e.direction === WheelDirection.up ? 1.1 : e.direction === WheelDirection.down ? 0.9 : 1;
		this.canvas.matrix.scale(factor, factor, point);
		this.canvas.render();
	}
	// #endif
}